name: shell commands

on: [push]

jobs:
    runshell:
        runs-on: ubuntu-latest
        steps:
        - name: print string
          run: echo "Integracao continua vai dominar o mundo"
        - name: faz uma parada
          run: |
              node -v
              npm -v